services:
  frontend:
    container_name: MELI_FRONTEND
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
    env_file:
      - .env.frontend
    ports:
      - "${FRONT_PORT}:80"
  backend:
    container_name: MELI_BACKEND
    healthcheck:
      test: "wget --quiet --spider http://localhost:3000/api/shared/health-check || exit 1"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s
    build:
      dockerfile: Dockerfile
      context: ./backend
      args:
        - PORT=3000
    restart: always
    environment:
      - PORT=3000
      - APP_GLOBAL_PREFIX=api
    env_file:
      - .env.backend
    ports:
      - "${BACK_PORT}:3000"
  frontend-coverage:
    container_name: MELI_FRONTEND_COVERAGE
    build:
      dockerfile: DockerfileCoverage
      context: ./frontend
    restart: always
    ports:
      - "${FRONT_COVERAGE_PORT}:80"
  backend-coverage:
    container_name: MELI_BACKEND_COVERAGE
    build:
      dockerfile: DockerfileCoverage
      context: ./backend
    restart: always
    ports:
      - "${BACK_COVERAGE_PORT}:80"